
# Efinity Interface Designer SDC
# Version: 2023.1.150.3.11
# Date: 2023-08-21 22:29

# Copyright (C) 2017 - 2023 Efinix Inc. All rights reserved.

# Device: Ti180J484
# Project: ti180-tsemac-linux
# Timing Model: C4 (final)

# PLL Constraints
#################
### Clock for Soc
create_clock -period 5.0000 io_peripheralClk
create_clock -period 5.0000 io_systemClk
create_clock -period 8.0000 io_memoryClk
create_clock -period 7.5008 ddr_pll_CLKOUT0
create_clock -period 100.00 jtag_inst1_TCK

### Clock for Picam and HDMI
create_clock -period 10.0000 mipi_rx_cfgclk
create_clock -period 10.0000 mipi_pclk
create_clock -period 40.0000 hdmi_clk
create_clock -period 13.4615 hdmi_yuv_clk
create_clock -period 6.4000 [get_ports {mipi_dphy_rx_inst1_LP_CLK}]
create_clock -period 6.4000 [get_ports {mipi_dphy_rx_inst1_ESC_LAN0_CLK}]
create_clock -period 6.4000 [get_ports {mipi_dphy_rx_inst1_ESC_LAN1_CLK}]
create_clock -period 6.4000 [get_ports {mipi_dphy_rx_inst1_WORD_CLKOUT_HS}]


### Clock for TSEMAC
create_clock -period 8.0000 io_tseClk
create_clock -period 8.0000 rgmii_rxc_dum
create_clock -waveform {6.667 10.667} -period 8.000 -name rgmii_rxc [get_ports {rgmii_rxc}]
create_clock -waveform {2.0000 6.0000} -period 8.0000 io_tseClk_90

set_clock_groups -exclusive -group {io_peripheralClk} -group {io_systemClk} -group {io_memoryClk} -group {jtag_inst1_TCK} -group {mipi_pclk} -group {hdmi_clk} -group {hdmi_yuv_clk} -group {mipi_rx_cfgclk} -group {mipi_dphy_rx_inst1_WORD_CLKOUT_HS} -group {io_tseClk} -group {io_tseClk_90} -group {rgmii_rxc_slow} -group {rgmii_rxc}

#Display & Camera Related Constraints
##############################
set_input_delay -clock hdmi_clk -reference_pin [get_ports {hdmi_clk~CLKOUT~333~335}] -max 0.414 [get_ports {hdmi_scl_read}]
set_input_delay -clock hdmi_clk -reference_pin [get_ports {hdmi_clk~CLKOUT~333~335}] -min 0.276 [get_ports {hdmi_scl_read}]
set_output_delay -clock hdmi_clk -reference_pin [get_ports {hdmi_clk~CLKOUT~333~337}] -max 0.263 [get_ports {hdmi_scl_writeEnable}]
set_output_delay -clock hdmi_clk -reference_pin [get_ports {hdmi_clk~CLKOUT~333~337}] -min -0.140 [get_ports {hdmi_scl_writeEnable}]
set_input_delay -clock hdmi_clk -reference_pin [get_ports {hdmi_clk~CLKOUT~333~334}] -max 0.414 [get_ports {hdmi_sda_read}]
set_input_delay -clock hdmi_clk -reference_pin [get_ports {hdmi_clk~CLKOUT~333~334}] -min 0.276 [get_ports {hdmi_sda_read}]
set_output_delay -clock hdmi_clk -reference_pin [get_ports {hdmi_clk~CLKOUT~333~336}] -max 0.263 [get_ports {hdmi_sda_writeEnable}]
set_output_delay -clock hdmi_clk -reference_pin [get_ports {hdmi_clk~CLKOUT~333~336}] -min -0.140 [get_ports {hdmi_sda_writeEnable}]
set_input_delay -clock io_peripheralClk -reference_pin [get_ports {io_peripheralClk~CLKOUT~333~20}] -max 0.691 [get_ports {i_cam_scl}]
set_input_delay -clock io_peripheralClk -reference_pin [get_ports {io_peripheralClk~CLKOUT~333~20}] -min 0.461 [get_ports {i_cam_scl}]
set_output_delay -clock io_peripheralClk -reference_pin [get_ports {io_peripheralClk~CLKOUT~333~21}] -max 0.061 [get_ports {o_cam_scl_oe}]
set_output_delay -clock io_peripheralClk -reference_pin [get_ports {io_peripheralClk~CLKOUT~333~21}] -min -0.026 [get_ports {o_cam_scl_oe}]
set_input_delay -clock io_peripheralClk -reference_pin [get_ports {io_peripheralClk~CLKOUT~333~22}] -max 0.691 [get_ports {i_cam_sda}]
set_input_delay -clock io_peripheralClk -reference_pin [get_ports {io_peripheralClk~CLKOUT~333~22}] -min 0.461 [get_ports {i_cam_sda}]
set_output_delay -clock io_peripheralClk -reference_pin [get_ports {io_peripheralClk~CLKOUT~333~23}] -max 0.061 [get_ports {o_cam_sda_oe}]
set_output_delay -clock io_peripheralClk -reference_pin [get_ports {io_peripheralClk~CLKOUT~333~23}] -min -0.026 [get_ports {o_cam_sda_oe}]

#SD Card Related Constraints
##############################
set_output_delay -clock io_peripheralClk -reference_pin [get_ports {io_peripheralClk~CLKOUT~333~610}] -max 0.079 [get_ports {sd_clk_hi}]
set_output_delay -clock io_peripheralClk -reference_pin [get_ports {io_peripheralClk~CLKOUT~333~610}] -min -0.045 [get_ports {sd_clk_hi}]

#SPI Constraints
#########################
set_output_delay -clock io_peripheralClk -reference_pin [get_ports {io_peripheralClk~CLKOUT~18~1}] -max 0.263 [get_ports {system_spi_0_io_sclk_write}]
set_output_delay -clock io_peripheralClk -reference_pin [get_ports {io_peripheralClk~CLKOUT~18~1}] -min -0.140 [get_ports {system_spi_0_io_sclk_write}]
set_output_delay -clock io_peripheralClk -reference_pin [get_ports {io_peripheralClk~CLKOUT~78~1}] -max 0.263 [get_ports {system_spi_0_io_ss}]
set_output_delay -clock io_peripheralClk -reference_pin [get_ports {io_peripheralClk~CLKOUT~78~1}] -min -0.140 [get_ports {system_spi_0_io_ss}]
set_input_delay -clock io_peripheralClk -reference_pin [get_ports {io_peripheralClk~CLKOUT~85~1}] -max 0.414 [get_ports {system_spi_0_io_data_0_read}]
set_input_delay -clock io_peripheralClk -reference_pin [get_ports {io_peripheralClk~CLKOUT~85~1}] -min 0.276 [get_ports {system_spi_0_io_data_0_read}]
set_output_delay -clock io_peripheralClk -reference_pin [get_ports {io_peripheralClk~CLKOUT~87~1}] -max 0.263 [get_ports {system_spi_0_io_data_0_write}]
set_output_delay -clock io_peripheralClk -reference_pin [get_ports {io_peripheralClk~CLKOUT~87~1}] -min -0.140 [get_ports {system_spi_0_io_data_0_write}]
set_output_delay -clock io_peripheralClk -reference_pin [get_ports {io_peripheralClk~CLKOUT~87~1}] -max 0.263 [get_ports {system_spi_0_io_data_0_writeEnable}]
set_output_delay -clock io_peripheralClk -reference_pin [get_ports {io_peripheralClk~CLKOUT~87~1}] -min -0.140 [get_ports {system_spi_0_io_data_0_writeEnable}]
set_input_delay -clock io_peripheralClk -reference_pin [get_ports {io_peripheralClk~CLKOUT~86~1}] -max 0.414 [get_ports {system_spi_0_io_data_1_read}]
set_input_delay -clock io_peripheralClk -reference_pin [get_ports {io_peripheralClk~CLKOUT~86~1}] -min 0.276 [get_ports {system_spi_0_io_data_1_read}]
set_output_delay -clock io_peripheralClk -reference_pin [get_ports {io_peripheralClk~CLKOUT~88~1}] -max 0.263 [get_ports {system_spi_0_io_data_1_write}]
set_output_delay -clock io_peripheralClk -reference_pin [get_ports {io_peripheralClk~CLKOUT~88~1}] -min -0.140 [get_ports {system_spi_0_io_data_1_write}]
set_output_delay -clock io_peripheralClk -reference_pin [get_ports {io_peripheralClk~CLKOUT~88~1}] -max 0.263 [get_ports {system_spi_0_io_data_1_writeEnable}]
set_output_delay -clock io_peripheralClk -reference_pin [get_ports {io_peripheralClk~CLKOUT~88~1}] -min -0.140 [get_ports {system_spi_0_io_data_1_writeEnable}]

#TSEMAC Related Constraints
#########################
set_input_delay -clock rgmii_rxc -reference_pin [get_ports {rgmii_rxc~CLKOUT~333~571}] -max 0.414 [get_ports {rgmii_rx_ctl_LO rgmii_rx_ctl_HI}]
set_input_delay -clock rgmii_rxc -reference_pin [get_ports {rgmii_rxc~CLKOUT~333~571}] -min 0.276 [get_ports {rgmii_rx_ctl_LO rgmii_rx_ctl_HI}]
set_input_delay -clock rgmii_rxc -reference_pin [get_ports {rgmii_rxc~CLKOUT~333~560}] -max 0.414 [get_ports {rgmii_rxd_HI[0] rgmii_rxd_LO[0]}]
set_input_delay -clock rgmii_rxc -reference_pin [get_ports {rgmii_rxc~CLKOUT~333~560}] -min 0.276 [get_ports {rgmii_rxd_HI[0] rgmii_rxd_LO[0]}]
set_input_delay -clock rgmii_rxc -reference_pin [get_ports {rgmii_rxc~CLKOUT~333~559}] -max 0.414 [get_ports {rgmii_rxd_HI[1] rgmii_rxd_LO[1]}]
set_input_delay -clock rgmii_rxc -reference_pin [get_ports {rgmii_rxc~CLKOUT~333~559}] -min 0.276 [get_ports {rgmii_rxd_HI[1] rgmii_rxd_LO[1]}]
set_input_delay -clock rgmii_rxc -reference_pin [get_ports {rgmii_rxc~CLKOUT~333~548}] -max 0.414 [get_ports {rgmii_rxd_HI[2] rgmii_rxd_LO[2]}]
set_input_delay -clock rgmii_rxc -reference_pin [get_ports {rgmii_rxc~CLKOUT~333~548}] -min 0.276 [get_ports {rgmii_rxd_HI[2] rgmii_rxd_LO[2]}]
set_input_delay -clock rgmii_rxc -reference_pin [get_ports {rgmii_rxc~CLKOUT~333~547}] -max 0.414 [get_ports {rgmii_rxd_HI[3] rgmii_rxd_LO[3]}]
set_input_delay -clock rgmii_rxc -reference_pin [get_ports {rgmii_rxc~CLKOUT~333~547}] -min 0.276 [get_ports {rgmii_rxd_HI[3] rgmii_rxd_LO[3]}]
set_output_delay -clock io_tseClk -reference_pin [get_ports {io_tseClk~CLKOUT~333~359}] -max 0.263 [get_ports {rgmii_tx_ctl_LO rgmii_tx_ctl_HI}]
set_output_delay -clock io_tseClk -reference_pin [get_ports {io_tseClk~CLKOUT~333~359}] -min -0.140 [get_ports {rgmii_tx_ctl_LO rgmii_tx_ctl_HI}]
set_output_delay -clock io_tseClk_90 -reference_pin [get_ports {io_tseClk_90~CLKOUT~333~420}] -max 0.263 [get_ports {rgmii_txc_LO rgmii_txc_HI}]
set_output_delay -clock io_tseClk_90 -reference_pin [get_ports {io_tseClk_90~CLKOUT~333~420}] -min -0.140 [get_ports {rgmii_txc_LO rgmii_txc_HI}]
set_output_delay -clock io_tseClk -reference_pin [get_ports {io_tseClk~CLKOUT~333~385}] -max 0.263 [get_ports {rgmii_txd_LO[0] rgmii_txd_HI[0]}]
set_output_delay -clock io_tseClk -reference_pin [get_ports {io_tseClk~CLKOUT~333~385}] -min -0.140 [get_ports {rgmii_txd_LO[0] rgmii_txd_HI[0]}]
set_output_delay -clock io_tseClk -reference_pin [get_ports {io_tseClk~CLKOUT~333~384}] -max 0.263 [get_ports {rgmii_txd_LO[1] rgmii_txd_HI[1]}]
set_output_delay -clock io_tseClk -reference_pin [get_ports {io_tseClk~CLKOUT~333~384}] -min -0.140 [get_ports {rgmii_txd_LO[1] rgmii_txd_HI[1]}]
set_output_delay -clock io_tseClk -reference_pin [get_ports {io_tseClk~CLKOUT~333~349}] -max 0.263 [get_ports {rgmii_txd_LO[2] rgmii_txd_HI[2]}]
set_output_delay -clock io_tseClk -reference_pin [get_ports {io_tseClk~CLKOUT~333~349}] -min -0.140 [get_ports {rgmii_txd_LO[2] rgmii_txd_HI[2]}]
set_output_delay -clock io_tseClk -reference_pin [get_ports {io_tseClk~CLKOUT~333~348}] -max 0.263 [get_ports {rgmii_txd_LO[3] rgmii_txd_HI[3]}]
set_output_delay -clock io_tseClk -reference_pin [get_ports {io_tseClk~CLKOUT~333~348}] -min -0.140 [get_ports {rgmii_txd_LO[3] rgmii_txd_HI[3]}]

# JTAG Constraints
####################
# create_clock -period <USER_PERIOD> [get_ports {jtag_inst1_TCK}]
set_output_delay -clock jtag_inst1_TCK -max 1.387 [get_ports {jtag_inst1_TDO}]
set_output_delay -clock jtag_inst1_TCK -min 0.555 [get_ports {jtag_inst1_TDO}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -max 0.603 [get_ports {jtag_inst1_CAPTURE}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -min 0.282 [get_ports {jtag_inst1_CAPTURE}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -max 1.191 [get_ports {jtag_inst1_RESET}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -min 0.682 [get_ports {jtag_inst1_RESET}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -max 0.593 [get_ports {jtag_inst1_SEL}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -min 0.344 [get_ports {jtag_inst1_SEL}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -max 0.564 [get_ports {jtag_inst1_UPDATE}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -min 0.362 [get_ports {jtag_inst1_UPDATE}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -max 0.575 [get_ports {jtag_inst1_SHIFT}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -min 0.294 [get_ports {jtag_inst1_SHIFT}]

# MIPI DPHY RX Constraints
#####################################
set_output_delay -clock mipi_dphy_rx_inst1_WORD_CLKOUT_HS -reference_pin [get_ports {mipi_dphy_rx_inst1_WORD_CLKOUT_HS~CLKOUT~1~38}] -max 0.835 [get_ports {mipi_dphy_rx_inst1_RST0_N}]
set_output_delay -clock mipi_dphy_rx_inst1_WORD_CLKOUT_HS -reference_pin [get_ports {mipi_dphy_rx_inst1_WORD_CLKOUT_HS~CLKOUT~1~38}] -min 0.089 [get_ports {mipi_dphy_rx_inst1_RST0_N}]
set_input_delay -clock mipi_dphy_rx_inst1_ESC_LAN0_CLK -max 4.343 [get_ports {mipi_dphy_rx_inst1_RX_DATA_ESC[*]}]
set_input_delay -clock mipi_dphy_rx_inst1_ESC_LAN0_CLK -min 2.895 [get_ports {mipi_dphy_rx_inst1_RX_DATA_ESC[*]}]
set_input_delay -clock mipi_dphy_rx_inst1_ESC_LAN0_CLK -max 4.039 [get_ports {mipi_dphy_rx_inst1_RX_LPDT_ESC}]
set_input_delay -clock mipi_dphy_rx_inst1_ESC_LAN0_CLK -min 2.693 [get_ports {mipi_dphy_rx_inst1_RX_LPDT_ESC}]
set_input_delay -clock mipi_dphy_rx_inst1_ESC_LAN0_CLK -max 3.907 [get_ports {mipi_dphy_rx_inst1_RX_TRIGGER_ESC[3] mipi_dphy_rx_inst1_RX_TRIGGER_ESC[2] mipi_dphy_rx_inst1_RX_TRIGGER_ESC[1] mipi_dphy_rx_inst1_RX_TRIGGER_ESC[0]}]
set_input_delay -clock mipi_dphy_rx_inst1_ESC_LAN0_CLK -min 2.605 [get_ports {mipi_dphy_rx_inst1_RX_TRIGGER_ESC[3] mipi_dphy_rx_inst1_RX_TRIGGER_ESC[2] mipi_dphy_rx_inst1_RX_TRIGGER_ESC[1] mipi_dphy_rx_inst1_RX_TRIGGER_ESC[0]}]
set_input_delay -clock mipi_dphy_rx_inst1_ESC_LAN0_CLK -max 3.387 [get_ports {mipi_dphy_rx_inst1_RX_ULPS_ESC_LAN0}]
set_input_delay -clock mipi_dphy_rx_inst1_ESC_LAN0_CLK -min 2.258 [get_ports {mipi_dphy_rx_inst1_RX_ULPS_ESC_LAN0}]
set_input_delay -clock mipi_dphy_rx_inst1_ESC_LAN0_CLK -max 3.465 [get_ports {mipi_dphy_rx_inst1_RX_VALID_ESC}]
set_input_delay -clock mipi_dphy_rx_inst1_ESC_LAN0_CLK -min 2.310 [get_ports {mipi_dphy_rx_inst1_RX_VALID_ESC}]
set_input_delay -clock mipi_dphy_rx_inst1_ESC_LAN1_CLK -max 3.783 [get_ports {mipi_dphy_rx_inst1_RX_ULPS_ESC_LAN1}]
set_input_delay -clock mipi_dphy_rx_inst1_ESC_LAN1_CLK -min 2.522 [get_ports {mipi_dphy_rx_inst1_RX_ULPS_ESC_LAN1}]
set_input_delay -clock mipi_dphy_rx_inst1_WORD_CLKOUT_HS -reference_pin [get_ports {mipi_dphy_rx_inst1_WORD_CLKOUT_HS~CLKOUT~1~38}] -max 1.607 [get_ports {mipi_dphy_rx_inst1_ERR_SOT_HS_LAN0}]
set_input_delay -clock mipi_dphy_rx_inst1_WORD_CLKOUT_HS -reference_pin [get_ports {mipi_dphy_rx_inst1_WORD_CLKOUT_HS~CLKOUT~1~38}] -min 1.071 [get_ports {mipi_dphy_rx_inst1_ERR_SOT_HS_LAN0}]
set_input_delay -clock mipi_dphy_rx_inst1_WORD_CLKOUT_HS -reference_pin [get_ports {mipi_dphy_rx_inst1_WORD_CLKOUT_HS~CLKOUT~1~38}] -max 1.619 [get_ports {mipi_dphy_rx_inst1_ERR_SOT_HS_LAN1}]
set_input_delay -clock mipi_dphy_rx_inst1_WORD_CLKOUT_HS -reference_pin [get_ports {mipi_dphy_rx_inst1_WORD_CLKOUT_HS~CLKOUT~1~38}] -min 1.079 [get_ports {mipi_dphy_rx_inst1_ERR_SOT_HS_LAN1}]
set_input_delay -clock mipi_dphy_rx_inst1_WORD_CLKOUT_HS -reference_pin [get_ports {mipi_dphy_rx_inst1_WORD_CLKOUT_HS~CLKOUT~1~38}] -max 1.667 [get_ports {mipi_dphy_rx_inst1_ERR_SOT_SYNC_HS_LAN0}]
set_input_delay -clock mipi_dphy_rx_inst1_WORD_CLKOUT_HS -reference_pin [get_ports {mipi_dphy_rx_inst1_WORD_CLKOUT_HS~CLKOUT~1~38}] -min 1.112 [get_ports {mipi_dphy_rx_inst1_ERR_SOT_SYNC_HS_LAN0}]
set_input_delay -clock mipi_dphy_rx_inst1_WORD_CLKOUT_HS -reference_pin [get_ports {mipi_dphy_rx_inst1_WORD_CLKOUT_HS~CLKOUT~1~38}] -max 1.613 [get_ports {mipi_dphy_rx_inst1_ERR_SOT_SYNC_HS_LAN1}]
set_input_delay -clock mipi_dphy_rx_inst1_WORD_CLKOUT_HS -reference_pin [get_ports {mipi_dphy_rx_inst1_WORD_CLKOUT_HS~CLKOUT~1~38}] -min 1.075 [get_ports {mipi_dphy_rx_inst1_ERR_SOT_SYNC_HS_LAN1}]
set_input_delay -clock mipi_dphy_rx_inst1_WORD_CLKOUT_HS -reference_pin [get_ports {mipi_dphy_rx_inst1_WORD_CLKOUT_HS~CLKOUT~1~38}] -max 1.627 [get_ports {mipi_dphy_rx_inst1_RX_ACTIVE_HS_LAN0}]
set_input_delay -clock mipi_dphy_rx_inst1_WORD_CLKOUT_HS -reference_pin [get_ports {mipi_dphy_rx_inst1_WORD_CLKOUT_HS~CLKOUT~1~38}] -min 1.085 [get_ports {mipi_dphy_rx_inst1_RX_ACTIVE_HS_LAN0}]
set_input_delay -clock mipi_dphy_rx_inst1_WORD_CLKOUT_HS -reference_pin [get_ports {mipi_dphy_rx_inst1_WORD_CLKOUT_HS~CLKOUT~1~38}] -max 1.644 [get_ports {mipi_dphy_rx_inst1_RX_ACTIVE_HS_LAN1}]
set_input_delay -clock mipi_dphy_rx_inst1_WORD_CLKOUT_HS -reference_pin [get_ports {mipi_dphy_rx_inst1_WORD_CLKOUT_HS~CLKOUT~1~38}] -min 1.096 [get_ports {mipi_dphy_rx_inst1_RX_ACTIVE_HS_LAN1}]
set_input_delay -clock mipi_dphy_rx_inst1_WORD_CLKOUT_HS -reference_pin [get_ports {mipi_dphy_rx_inst1_WORD_CLKOUT_HS~CLKOUT~1~38}] -max 1.693 [get_ports {mipi_dphy_rx_inst1_RX_DATA_HS_LAN0[*]}]
set_input_delay -clock mipi_dphy_rx_inst1_WORD_CLKOUT_HS -reference_pin [get_ports {mipi_dphy_rx_inst1_WORD_CLKOUT_HS~CLKOUT~1~38}] -min 1.128 [get_ports {mipi_dphy_rx_inst1_RX_DATA_HS_LAN0[*]}]
set_input_delay -clock mipi_dphy_rx_inst1_WORD_CLKOUT_HS -reference_pin [get_ports {mipi_dphy_rx_inst1_WORD_CLKOUT_HS~CLKOUT~1~38}] -max 1.723 [get_ports {mipi_dphy_rx_inst1_RX_DATA_HS_LAN1[*]}]
set_input_delay -clock mipi_dphy_rx_inst1_WORD_CLKOUT_HS -reference_pin [get_ports {mipi_dphy_rx_inst1_WORD_CLKOUT_HS~CLKOUT~1~38}] -min 1.149 [get_ports {mipi_dphy_rx_inst1_RX_DATA_HS_LAN1[*]}]
set_input_delay -clock mipi_dphy_rx_inst1_WORD_CLKOUT_HS -reference_pin [get_ports {mipi_dphy_rx_inst1_WORD_CLKOUT_HS~CLKOUT~1~38}] -max 1.723 [get_ports {mipi_dphy_rx_inst1_RX_SKEW_CAL_HS_LAN0}]
set_input_delay -clock mipi_dphy_rx_inst1_WORD_CLKOUT_HS -reference_pin [get_ports {mipi_dphy_rx_inst1_WORD_CLKOUT_HS~CLKOUT~1~38}] -min 1.149 [get_ports {mipi_dphy_rx_inst1_RX_SKEW_CAL_HS_LAN0}]
set_input_delay -clock mipi_dphy_rx_inst1_WORD_CLKOUT_HS -reference_pin [get_ports {mipi_dphy_rx_inst1_WORD_CLKOUT_HS~CLKOUT~1~38}] -max 1.656 [get_ports {mipi_dphy_rx_inst1_RX_SKEW_CAL_HS_LAN1}]
set_input_delay -clock mipi_dphy_rx_inst1_WORD_CLKOUT_HS -reference_pin [get_ports {mipi_dphy_rx_inst1_WORD_CLKOUT_HS~CLKOUT~1~38}] -min 1.104 [get_ports {mipi_dphy_rx_inst1_RX_SKEW_CAL_HS_LAN1}]
set_input_delay -clock mipi_dphy_rx_inst1_WORD_CLKOUT_HS -reference_pin [get_ports {mipi_dphy_rx_inst1_WORD_CLKOUT_HS~CLKOUT~1~38}] -max 1.707 [get_ports {mipi_dphy_rx_inst1_RX_SYNC_HS_LAN0}]
set_input_delay -clock mipi_dphy_rx_inst1_WORD_CLKOUT_HS -reference_pin [get_ports {mipi_dphy_rx_inst1_WORD_CLKOUT_HS~CLKOUT~1~38}] -min 1.138 [get_ports {mipi_dphy_rx_inst1_RX_SYNC_HS_LAN0}]
set_input_delay -clock mipi_dphy_rx_inst1_WORD_CLKOUT_HS -reference_pin [get_ports {mipi_dphy_rx_inst1_WORD_CLKOUT_HS~CLKOUT~1~38}] -max 1.632 [get_ports {mipi_dphy_rx_inst1_RX_SYNC_HS_LAN1}]
set_input_delay -clock mipi_dphy_rx_inst1_WORD_CLKOUT_HS -reference_pin [get_ports {mipi_dphy_rx_inst1_WORD_CLKOUT_HS~CLKOUT~1~38}] -min 1.088 [get_ports {mipi_dphy_rx_inst1_RX_SYNC_HS_LAN1}]
set_input_delay -clock mipi_dphy_rx_inst1_WORD_CLKOUT_HS -reference_pin [get_ports {mipi_dphy_rx_inst1_WORD_CLKOUT_HS~CLKOUT~1~38}] -max 1.645 [get_ports {mipi_dphy_rx_inst1_RX_VALID_HS_LAN0}]
set_input_delay -clock mipi_dphy_rx_inst1_WORD_CLKOUT_HS -reference_pin [get_ports {mipi_dphy_rx_inst1_WORD_CLKOUT_HS~CLKOUT~1~38}] -min 1.097 [get_ports {mipi_dphy_rx_inst1_RX_VALID_HS_LAN0}]
set_input_delay -clock mipi_dphy_rx_inst1_WORD_CLKOUT_HS -reference_pin [get_ports {mipi_dphy_rx_inst1_WORD_CLKOUT_HS~CLKOUT~1~38}] -max 1.612 [get_ports {mipi_dphy_rx_inst1_RX_VALID_HS_LAN1}]
set_input_delay -clock mipi_dphy_rx_inst1_WORD_CLKOUT_HS -reference_pin [get_ports {mipi_dphy_rx_inst1_WORD_CLKOUT_HS~CLKOUT~1~38}] -min 1.075 [get_ports {mipi_dphy_rx_inst1_RX_VALID_HS_LAN1}]
set_input_delay -clock mipi_dphy_rx_inst1_WORD_CLKOUT_HS -reference_pin [get_ports {mipi_dphy_rx_inst1_WORD_CLKOUT_HS~CLKOUT~1~38}] -max 1.647 [get_ports {mipi_dphy_rx_inst1_STOPSTATE_LAN0}]
set_input_delay -clock mipi_dphy_rx_inst1_WORD_CLKOUT_HS -reference_pin [get_ports {mipi_dphy_rx_inst1_WORD_CLKOUT_HS~CLKOUT~1~38}] -min 1.098 [get_ports {mipi_dphy_rx_inst1_STOPSTATE_LAN0}]
set_input_delay -clock mipi_dphy_rx_inst1_WORD_CLKOUT_HS -reference_pin [get_ports {mipi_dphy_rx_inst1_WORD_CLKOUT_HS~CLKOUT~1~38}] -max 1.592 [get_ports {mipi_dphy_rx_inst1_STOPSTATE_LAN1}]
set_input_delay -clock mipi_dphy_rx_inst1_WORD_CLKOUT_HS -reference_pin [get_ports {mipi_dphy_rx_inst1_WORD_CLKOUT_HS~CLKOUT~1~38}] -min 1.061 [get_ports {mipi_dphy_rx_inst1_STOPSTATE_LAN1}]


# DDR Constraints
#####################
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -max 3.675 [get_ports {DDR_AXI0_resetn}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -min -0.000 [get_ports {DDR_AXI0_resetn}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -max 2.310 [get_ports {io_ddrA_ar_payload_addr[*]}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -min -0.140 [get_ports {io_ddrA_ar_payload_addr[*]}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -max 2.310 [get_ports {io_ddrA_ar_apcmd}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -min -0.140 [get_ports {io_ddrA_ar_apcmd}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -max 2.310 [get_ports {io_ddrA_ar_payload_burst[1] io_ddrA_ar_payload_burst[0]}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -min -0.140 [get_ports {io_ddrA_ar_payload_burst[1] io_ddrA_ar_payload_burst[0]}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -max 2.310 [get_ports {io_ddrA_ar_payload_id[*]}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -min -0.140 [get_ports {io_ddrA_ar_payload_id[*]}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -max 2.310 [get_ports {io_ddrA_ar_payload_len[*]}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -min -0.140 [get_ports {io_ddrA_ar_payload_len[*]}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -max 2.310 [get_ports {io_ddrA_ar_payload_size[2] io_ddrA_ar_payload_size[1] io_ddrA_ar_payload_size[0]}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -min -0.140 [get_ports {io_ddrA_ar_payload_size[2] io_ddrA_ar_payload_size[1] io_ddrA_ar_payload_size[0]}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -max 2.310 [get_ports {io_ddrA_ar_valid}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -min -0.140 [get_ports {io_ddrA_ar_valid}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -max 2.310 [get_ports {io_ddrA_ar_payload_lock}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -min -0.140 [get_ports {io_ddrA_ar_payload_lock}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -max 2.310 [get_ports {io_ddrA_ar_payload_qos}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -min -0.140 [get_ports {io_ddrA_ar_payload_qos}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -max 2.310 [get_ports {io_ddrA_aw_payload_addr[*]}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -min -0.140 [get_ports {io_ddrA_aw_payload_addr[*]}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -max 2.310 [get_ports {io_ddrA_aw_apcmd}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -min -0.350 [get_ports {io_ddrA_aw_apcmd}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -max 2.310 [get_ports {io_ddrA_aw_payload_allstrb}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -min -0.140 [get_ports {io_ddrA_aw_payload_allstrb}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -max 2.310 [get_ports {io_ddrA_aw_payload_burst[1] io_ddrA_aw_payload_burst[0]}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -min -0.140 [get_ports {io_ddrA_aw_payload_burst[1] io_ddrA_aw_payload_burst[0]}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -max 2.310 [get_ports {io_ddrA_awcobuf}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -min -0.140 [get_ports {io_ddrA_awcobuf}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -max 2.310 [get_ports {io_ddrA_aw_payload_id[*]}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -min -0.140 [get_ports {io_ddrA_aw_payload_id[*]}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -max 2.310 [get_ports {io_ddrA_aw_payload_len[*]}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -min -0.140 [get_ports {io_ddrA_aw_payload_len[*]}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -max 2.310 [get_ports {io_ddrA_aw_payload_size[2] io_ddrA_aw_payload_size[1] io_ddrA_aw_payload_size[0]}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -min -0.140 [get_ports {io_ddrA_aw_payload_size[2] io_ddrA_aw_payload_size[1] io_ddrA_aw_payload_size[0]}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -max 2.310 [get_ports {io_ddrA_aw_valid}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -min -0.140 [get_ports {io_ddrA_aw_valid}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -max 2.310 [get_ports {io_ddrA_aw_payload_lock}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -min -0.140 [get_ports {io_ddrA_aw_payload_lock}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -max 2.310 [get_ports {io_ddrA_aw_payload_cache[3] io_ddrA_aw_payload_cache[2] io_ddrA_aw_payload_cache[1] io_ddrA_aw_payload_cache[0]}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -min -0.140 [get_ports {io_ddrA_aw_payload_cache[3] io_ddrA_aw_payload_cache[2] io_ddrA_aw_payload_cache[1] io_ddrA_aw_payload_cache[0]}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -max 2.310 [get_ports {io_ddrA_aw_payload_qos}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -min -0.140 [get_ports {io_ddrA_aw_payload_qos}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -max 2.310 [get_ports {io_ddrA_b_ready}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -min -0.140 [get_ports {io_ddrA_b_ready}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -max 2.310 [get_ports {io_ddrA_r_ready}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -min -0.140 [get_ports {io_ddrA_r_ready}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -max 2.310 [get_ports {io_ddrA_w_payload_data[*]}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -min -0.140 [get_ports {io_ddrA_w_payload_data[*]}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -max 2.310 [get_ports {io_ddrA_w_payload_last}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -min -0.140 [get_ports {io_ddrA_w_payload_last}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -max 2.310 [get_ports {io_ddrA_w_payload_strb[*]}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -min -0.140 [get_ports {io_ddrA_w_payload_strb[*]}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -max 2.310 [get_ports {io_ddrA_w_valid}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -min -0.140 [get_ports {io_ddrA_w_valid}]
set_input_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -max 2.625 [get_ports {io_ddrA_ar_ready}]
set_input_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -min 1.750 [get_ports {io_ddrA_ar_ready}]
set_input_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -max 2.520 [get_ports {io_ddrA_aw_ready}]
set_input_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -min 1.680 [get_ports {io_ddrA_aw_ready}]
set_input_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -max 2.520 [get_ports {io_ddrA_b_payload_id[*]}]
set_input_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -min 1.680 [get_ports {io_ddrA_b_payload_id[*]}]
set_input_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -max 2.625 [get_ports {io_ddrA_b_payload_resp[1] io_ddrA_b_payload_resp[0]}]
set_input_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -min 1.750 [get_ports {io_ddrA_b_payload_resp[1] io_ddrA_b_payload_resp[0]}]
set_input_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -max 2.625 [get_ports {io_ddrA_b_valid}]
set_input_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -min 1.750 [get_ports {io_ddrA_b_valid}]
set_input_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -max 2.625 [get_ports {io_ddrA_r_payload_data[*]}]
set_input_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -min 1.750 [get_ports {io_ddrA_r_payload_data[*]}]
set_input_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -max 2.625 [get_ports {io_ddrA_r_payload_id[*]}]
set_input_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -min 1.750 [get_ports {io_ddrA_r_payload_id[*]}]
set_input_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -max 2.625 [get_ports {io_ddrA_r_payload_last}]
set_input_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -min 1.750 [get_ports {io_ddrA_r_payload_last}]
set_input_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -max 2.625 [get_ports {io_ddrA_r_payload_resp[1] io_ddrA_r_payload_resp[0]}]
set_input_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -min 1.750 [get_ports {io_ddrA_r_payload_resp[1] io_ddrA_r_payload_resp[0]}]
set_input_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -max 2.625 [get_ports {io_ddrA_r_valid}]
set_input_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -min 1.750 [get_ports {io_ddrA_r_valid}]
set_input_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -max 2.625 [get_ports {io_ddrA_w_ready}]
set_input_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~2~150}] -min 1.750 [get_ports {io_ddrA_w_ready}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -max 3.675 [get_ports {DDR_AXI1_resetn}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -min -0.000 [get_ports {DDR_AXI1_resetn}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -max 2.310 [get_ports {io_ddrB_ar_payload_addr[*]}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -min -0.140 [get_ports {io_ddrB_ar_payload_addr[*]}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -max 2.310 [get_ports {io_ddrB_ar_apcmd}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -min -0.140 [get_ports {io_ddrB_ar_apcmd}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -max 2.310 [get_ports {io_ddrB_ar_payload_burst[1] io_ddrB_ar_payload_burst[0]}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -min -0.140 [get_ports {io_ddrB_ar_payload_burst[1] io_ddrB_ar_payload_burst[0]}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -max 2.310 [get_ports {io_ddrB_ar_payload_id[*]}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -min -0.140 [get_ports {io_ddrB_ar_payload_id[*]}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -max 2.310 [get_ports {io_ddrB_ar_payload_len[*]}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -min -0.140 [get_ports {io_ddrB_ar_payload_len[*]}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -max 2.310 [get_ports {io_ddrB_ar_payload_size[2] io_ddrB_ar_payload_size[1] io_ddrB_ar_payload_size[0]}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -min -0.140 [get_ports {io_ddrB_ar_payload_size[2] io_ddrB_ar_payload_size[1] io_ddrB_ar_payload_size[0]}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -max 2.310 [get_ports {io_ddrB_ar_valid}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -min -0.140 [get_ports {io_ddrB_ar_valid}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -max 2.310 [get_ports {io_ddrB_ar_payload_lock}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -min -0.140 [get_ports {io_ddrB_ar_payload_lock}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -max 2.310 [get_ports {io_ddrB_ar_payload_qos}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -min -0.140 [get_ports {io_ddrB_ar_payload_qos}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -max 2.310 [get_ports {io_ddrB_aw_payload_addr[*]}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -min -0.140 [get_ports {io_ddrB_aw_payload_addr[*]}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -max 2.310 [get_ports {io_ddrB_aw_apcmd}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -min -0.350 [get_ports {io_ddrB_aw_apcmd}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -max 2.310 [get_ports {io_ddrB_aw_payload_allstrb}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -min -0.140 [get_ports {io_ddrB_aw_payload_allstrb}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -max 2.310 [get_ports {io_ddrB_aw_payload_burst[1] io_ddrB_aw_payload_burst[0]}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -min -0.140 [get_ports {io_ddrB_aw_payload_burst[1] io_ddrB_aw_payload_burst[0]}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -max 2.310 [get_ports {io_ddrB_awcobuf}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -min -0.140 [get_ports {io_ddrB_awcobuf}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -max 2.310 [get_ports {io_ddrB_aw_payload_id[*]}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -min -0.140 [get_ports {io_ddrB_aw_payload_id[*]}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -max 2.310 [get_ports {io_ddrB_aw_payload_len[*]}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -min -0.140 [get_ports {io_ddrB_aw_payload_len[*]}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -max 2.310 [get_ports {io_ddrB_aw_payload_size[2] io_ddrB_aw_payload_size[1] io_ddrB_aw_payload_size[0]}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -min -0.140 [get_ports {io_ddrB_aw_payload_size[2] io_ddrB_aw_payload_size[1] io_ddrB_aw_payload_size[0]}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -max 2.310 [get_ports {io_ddrB_aw_valid}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -min -0.140 [get_ports {io_ddrB_aw_valid}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -max 2.310 [get_ports {io_ddrB_aw_payload_lock}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -min -0.140 [get_ports {io_ddrB_aw_payload_lock}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -max 2.310 [get_ports {io_ddrB_aw_payload_cache[3] io_ddrB_aw_payload_cache[2] io_ddrB_aw_payload_cache[1] io_ddrB_aw_payload_cache[0]}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -min -0.140 [get_ports {io_ddrB_aw_payload_cache[3] io_ddrB_aw_payload_cache[2] io_ddrB_aw_payload_cache[1] io_ddrB_aw_payload_cache[0]}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -max 2.310 [get_ports {io_ddrB_aw_payload_qos}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -min -0.140 [get_ports {io_ddrB_aw_payload_qos}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -max 2.310 [get_ports {io_ddrB_b_ready}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -min -0.140 [get_ports {io_ddrB_b_ready}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -max 2.310 [get_ports {io_ddrB_r_ready}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -min -0.140 [get_ports {io_ddrB_r_ready}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -max 2.310 [get_ports {io_ddrB_w_payload_data[*]}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -min -0.140 [get_ports {io_ddrB_w_payload_data[*]}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -max 2.310 [get_ports {io_ddrB_w_payload_last}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -min -0.140 [get_ports {io_ddrB_w_payload_last}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -max 2.310 [get_ports {io_ddrB_w_payload_strb[*]}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -min -0.140 [get_ports {io_ddrB_w_payload_strb[*]}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -max 2.310 [get_ports {io_ddrB_w_valid}]
set_output_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -min -0.140 [get_ports {io_ddrB_w_valid}]
set_input_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -max 2.625 [get_ports {io_ddrB_ar_ready}]
set_input_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -min 1.750 [get_ports {io_ddrB_ar_ready}]
set_input_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -max 2.520 [get_ports {io_ddrB_aw_ready}]
set_input_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -min 1.680 [get_ports {io_ddrB_aw_ready}]
set_input_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -max 2.520 [get_ports {io_ddrB_b_payload_id[*]}]
set_input_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -min 1.680 [get_ports {io_ddrB_b_payload_id[*]}]
set_input_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -max 2.625 [get_ports {io_ddrB_b_payload_resp[1] io_ddrB_b_payload_resp[0]}]
set_input_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -min 1.750 [get_ports {io_ddrB_b_payload_resp[1] io_ddrB_b_payload_resp[0]}]
set_input_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -max 2.625 [get_ports {io_ddrB_b_valid}]
set_input_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -min 1.750 [get_ports {io_ddrB_b_valid}]
set_input_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -max 2.625 [get_ports {io_ddrB_r_payload_data[*]}]
set_input_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -min 1.750 [get_ports {io_ddrB_r_payload_data[*]}]
set_input_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -max 2.625 [get_ports {io_ddrB_r_payload_id[*]}]
set_input_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -min 1.750 [get_ports {io_ddrB_r_payload_id[*]}]
set_input_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -max 2.625 [get_ports {io_ddrB_r_payload_last}]
set_input_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -min 1.750 [get_ports {io_ddrB_r_payload_last}]
set_input_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -max 2.625 [get_ports {io_ddrB_r_payload_resp[1] io_ddrB_r_payload_resp[0]}]
set_input_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -min 1.750 [get_ports {io_ddrB_r_payload_resp[1] io_ddrB_r_payload_resp[0]}]
set_input_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -max 2.625 [get_ports {io_ddrB_r_valid}]
set_input_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -min 1.750 [get_ports {io_ddrB_r_valid}]
set_input_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -max 2.625 [get_ports {io_ddrB_w_ready}]
set_input_delay -clock io_memoryClk -reference_pin [get_ports {io_memoryClk~CLKOUT~1~338}] -min 1.750 [get_ports {io_ddrB_w_ready}]




